### PR TITLE
Performance Audit 🎉  🚀 ✔️ 

### PR DESCRIPTION
**Pull request by Nizamuddin4493**
Performance Audit 🎉  🚀 ✔️ 
### Before performance audit:

EXPLAIN ANALYZE SELECT COUNT(*) FROM visits where animalS_id = 4;
EXPLAIN ANALYZE SELECT * FROM visits where vetS_id = 2;
EXPLAIN ANALYZE SELECT * FROM owners where email = 'owner_18327@mail.com';

### After performance audit

EXPLAIN ANALYZE SELECT COUNT(*) FROM visits where animalS_id = 4;
EXPLAIN ANALYZE SELECT * FROM visits where vetS_id = 2;
EXPLAIN ANALYZE SELECT * FROM owners where email = 'owner_18327@mail.com';

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Invalid Code Review Request ❌

Hi @Nizamuddin4493, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't have a professional readme. Make sure you have readme before proceeding for review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by AngomRanjan** [comment]
## Made Changes As Suggested

- Added Readme

**Comment by AngomRanjan** [comment]
## Made Changes As Suggested

- Added Readme

**Review by dasileker — APPROVED** [review]
### **Hi @AngomRanjan,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
